# Generated by Django 4.0.6 on 2022-11-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_rest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rest',
            name='city',
        ),
        migrations.RemoveField(
            model_name='rest',
            name='drive_time',
        ),
        migrations.RemoveField(
            model_name='rest',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='rest',
            name='state',
        ),
        migrations.RemoveField(
            model_name='rest',
            name='street_address',
        ),
        migrations.AddField(
            model_name='rest',
            name='address',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rest',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rest',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rest',
            name='my_rating',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='rest',
            name='category',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rest',
            name='notes',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rest',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True),
        ),
    ]
