# Generated by Django 4.1.3 on 2022-12-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_restaraunt_rest_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='miles',
            field=models.BooleanField(default=True),
        ),
    ]
