# Generated by Django 4.1.3 on 2022-12-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rest_miles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rest',
            name='miles',
        ),
    ]
